version: "3"
services:
  order-beverage-service:
    image: probir/vending-machine-microservices:latest
    hostname: order-beverage-service
    restart: always
    entrypoint: OrderBeverageService

  weather-service:
    image: probir/vending-machine-microservices:latest
    hostname: weather-service
    restart: always
    entrypoint: WeatherService

  beverage-preference-service:
    build:
      context: .
      dockerfile: ./src/BeveragePreferenceService/Dockerfile
    hostname: beverage-preference-service
    ports:
      - "9092:9092"
    networks:
      - vending-net
    restart: always

  nginx-thrift:
    image: yg397/openresty-thrift:xenial
    hostname: nginx-thrift
    ports:
      - 8080:8080
    restart: always
    volumes:
      - ./nginx_reverse_proxy/lua-scripts:/usr/local/openresty/nginx/lua-scripts
      - ./nginx_reverse_proxy/conf/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - ./gen-lua:/gen-lua

networks:
  vending-net:
    driver: bridge
